#!/bin/tcsh
#PBS -N rf_metrics_2000
#PBS -A NTDD0005
#PBS -l select=1:ncpus=128:mem=235GB
#PBS -l walltime=02:00:00
#PBS -q main@desched1
#PBS -j oe

source /etc/csh.cshrc
module load conda
conda activate my-npl-2023a

setenv HDF5_PLUGIN_PATH /glade/work/haiyingx/H5Z-ZFP-PLUGIN-unbiased/plugin
setenv OMP_NUM_THREADS 1
setenv OPENBLAS_NUM_THREADS 1
setenv MKL_NUM_THREADS 1
setenv NUMEXPR_NUM_THREADS 1
cd /glade/derecho/scratch/apinard/lcr/lcr/paper_submit

mkdir -p data

if (! $?TIMESTEPS) setenv TIMESTEPS 2000

python feature_generation/generate_features.py \
    --config multi_config_48.json \
    --quality-config rotated_config_48.json \
    --quality-config multi_config_48.json \
    --mode metrics \
    --variable-index $VARIABLE_INDEX \
    --compression-index $COMPRESSION_INDEX \
    --timesteps $TIMESTEPS \
    --workers 16 \
    --output-dir ./data \
    --metrics-dir ./metrics
