#!/bin/tcsh
#PBS -N rf_features_2000
#PBS -A NTDD0005
#PBS -l select=1:ncpus=16:mem=128GB
#PBS -l walltime=24:00:00
#PBS -q casper@casper-pbs
#PBS -j oe

source /etc/csh.cshrc
module load conda
conda activate my-npl-2023a

setenv HDF5_PLUGIN_PATH /glade/work/haiyingx/H5Z-ZFP-PLUGIN-unbiased/plugin
setenv OMP_NUM_THREADS 1
setenv OPENBLAS_NUM_THREADS 1
setenv MKL_NUM_THREADS 1
setenv NUMEXPR_NUM_THREADS 1
cd /glade/derecho/scratch/apinard/lcr/lcr/modeling

mkdir -p data

python feature_generation/generate_features.py \
    --config multi_config_48.json \
    --quality-config rotated_config_48.json \
    --quality-config multi_config_48.json \
    --mode features \
    --variable-index $VARIABLE_INDEX \
    --timesteps 2000 \
    --workers 16 \
    --output-dir ./data
