#!/bin/tcsh

set arrname = (PRECSL TAUY soa_a2_SRF TAUX CDNUMC TGCLDLWP PRECL soa_a1_SRF SHFLX dst_a3_SRF pom_a1_SRF bc_a1_SRF TGCLDIWP dst_a1_SRF LHFLX QFLX LWCF so4_a2_SRF WGUSTD so4_a3_SRF CLDMED so4_a1_SRF PBLH CLDHGH BURDENSEASALT SFCO2 FLNS BURDENDUST U10 SWCF CLDTOT WSPDSRFMX CLDLOW BURDENPOM BURDENBC AODDUST3 BURDENSO4 BURDENSOA AODVIS TMQ FSNS AODABS AODDUST1 FLNSC FSDS SRFRAD FSNT FSNTOA FLDS FLNT FLUT PRECC FSNSC TROP_P FLNTC FLUTC FSNTC FSNTOAC SFCO2_OCN TREFHTMN TSMN TSMX TREFHTMX TMCO2 TS TMCO2_FFF TREFHT PS TMCO2_LND TROP_T SFCO2_FFF PSL PHIS SOLIN SFCO2_LND OCNFRAC SNOWHLND SNOWHICE PRECSC ICEFRAC LANDFRAC)
foreach x ($arrname)
  qsub comp/$x.sh
end

sleep 15
ls